kind: pipeline
name: default

steps:
  - name: publish
    image: plugins/docker
    settings:
      username: nologin
      password:
        from_secret: registry_token
      repo: rg.nl-ams.scw.cloud/emanuelpina/mailygo
      registry: rg.nl-ams.scw.cloud
      tags: latest

trigger:
  branch:
  - master