kind: pipeline
name: default

steps:
  - name: publish
    image: plugins/docker
    settings:
      username: 
        from_secret: registry_username
      password:
        from_secret: registry_token
      repo: quay.io/emanuelpina/mailygo
      registry: quay.io
      tags: latest

trigger:
  branch:
  - master